name: "deploy-lock"
description: "Lock Action to support deployment locking for the branch-deploy Action"
author: "Grant Birkinbine"
branding:
  icon: 'lock'
  color: 'gray-dark'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
  environment:
    description: 'The explict environment to apply locking actions to when running in headless mode - OR the default environment to use when running in the context of IssueOps commands in a comment - Examples: production, development, etc - Use "global" for the global lock environment'
    required: true
    default: "production"
  environment_targets:
    description: 'Optional (or additional) target environments to select for use with lock/unlock. Example, "production,development,staging". Example  usage: `.lock development`, `.lock production`, `.unlock staging`'
    required: false
    default: "production,development,staging"
  lock_trigger:
    description: 'The string to look for in comments as an IssueOps lock trigger. Used for locking branch deployments on a specific branch. Example: "lock"'
    required: false
    default: ".lock"
  unlock_trigger:
    description: 'The string to look for in comments as an IssueOps unlock trigger. Used for unlocking branch deployments. Example: "unlock"'
    required: false
    default: ".unlock"
  reaction:
    description: 'If set, the specified emoji "reaction" is put on the comment to indicate that the trigger was detected. For example, "rocket" or "eyes"'
    required: false
    default: "eyes"
  lock_info_alias:
    description: 'An alias or shortcut to get details about the current lock (if it exists) Example: ".info"'
    required: false
    default: ".wcid"
  global_lock_flag:
    description: 'The flag to pass into the lock command to lock all environments. Example: "--global"'
    required: false
    default: "--global"
  prefix_only:
    description: 'If "false", the trigger can match anywhere in the comment'
    required: false
    default: "true"
  mode:
    description: 'The mode to use "lock", "unlock", or "check". If not provided, the default mode assumes the workflow is not headless and triggered by a comment on a pull request - Example: .lock / .unlock'
    required: false
  reason:
    description: Reason for claiming the deployment lock for this repository
    required: false
outputs:
  triggered:
    description: 'The string "true" if the trigger was found, otherwise the string "false"'
  comment_id:
    description: The comment id which triggered this deployment (if it was not headless)
  type:
    description: The type of trigger which was found - 'lock', 'unlock', or 'info-info-alias'
  comment_body:
    description: The comment body which triggered this action (if it was not headless)
  headless:
    description: 'The string "true" if the run was headless, otherwise the string "false" - Headless in this context would be if the "mode" was set and the Action was not invoked by a comment on a pull request'
  locked:
    description: 'If the mode is set to "check", this output will be "true" if a lock exists, otherwise "false"'
  lock_environment:
    description: When running in headless mode and the "mode" is set to "check", this output will be the environment name that holds the lock, otherwise it will be empty
  branch:
    description: 'If the mode is set to "check", this output will be the branch name that holds the lock, otherwise it will be empty'
  created_by:
    description: 'If the mode is set to "check", this output will be the user that holds the lock, otherwise it will be empty'
  created_at:
    description: 'If the mode is set to "check", this output will be the ISO 8601 format date that the lock was claimed, otherwise it will be empty'
  reason:
    description: 'If the mode is set to "check", this output will be the reason the deployment lock was claimed, otherwise it will be empty'
  link:
    description: 'If the mode is set to "check", this output will be the link to the GitHub issue comment or action run that claimed the lock, otherwise it will be empty'
  global_lock_claimed:
    description: 'The string "true" if the global lock was claimed'
  global_lock_released:
    description: 'The string "true" if the global lock was released'
runs:
  using: "node20"
  main: "dist/index.js"
